### PR TITLE
Update portfolios.json

### PR DESCRIPTION
**Pull request by nino070**
Hi, CARIW and CARIEM are also available through ING and DeGiro

### CODE REVIEW

**Comment by nicwortel** [comment]
Thanks @nino070!

**Comment by thoutenbos** [comment]
Is the pricing for DeGiro correct now? As it is listed as “free”.
Are both mutual funds parts of the kernselectie?

**Comment by nicwortel** [comment]
> Is the pricing for DeGiro correct now? As it is listed as “free”.
Are both mutual funds part of the kernselectie?

Sorry, I forgot to reply to this! The Cardano funds are indeed not part of the 'kernselectie'.

The changes introduced in ecbb6990510546676c99f6ac3a97774029405a70 should fix this by introducing the concept of 'fund selections' such as the kernselectie and making sure that only funds which are included in the list get the discount on the transaction fees.

This has moved DEGIRO to the second place for the Cardano funds for the default inputs.

**Comment by thoutenbos** [comment]
I think the "Service Fee" for DeGiro is still missing. This is 0,2% per year for Mutual funds on Euronext.

**Comment by nicwortel** [comment]
Yes, you are correct. Unfortunately, in the current implementation the Kernselectie can only affect transaction costs, not service fees. I'm afraid it will be quite some work to modify the code, as currently it just calculates the service fee based on the total value of the portfolio without access to more detailed information.

I guess the easiest solution for now is to create a second broker again just for this portfolio (CARIW + CARIEM), where the service fee is set to 0.20%.

**Pull request merged**
